name: Add Your Website
description: Submit your personal website to the gallery
title: "Add: [Your Website Name]"
labels: ["new-website"]
body:
  - type: markdown
    attributes:
      value: |
        # 🌟 Thanks for submitting your website!
        
        Fill out this form and i'll add your website to the gallery. It'll only take a minute!
        
  - type: input
    id: name
    attributes:
      label: Your Name
      description: How should we display your name in the gallery?
      placeholder: "John Doe"
    validations:
      required: true
      
  - type: input
    id: url
    attributes:
      label: Website URL
      description: The full URL of your website (including https://)
      placeholder: "https://example.com"
    validations:
      required: true
      
  - type: dropdown
    id: location
    attributes:
      label: Location
      description: Where are you based? Choose 'Earth' if you prefer not to specify a country, or 'Other' if your country is not listed
      options:
        - Earth 🌍
        - Digital Nomad 🌎
        - Other 🌐
        - Afghanistan 🇦🇫
        - Albania 🇦🇱
        - Algeria 🇩🇿
        - Andorra 🇦🇩
        - Argentina 🇦🇷
        - Australia 🇦🇺
        - Austria 🇦🇹
        - Belgium 🇧🇪
        - Brazil 🇧🇷
        - Bulgaria 🇧🇬
        - Canada 🇨🇦
        - Chile 🇨🇱
        - China 🇨🇳
        - Croatia 🇭🇷
        - Czech Republic 🇨🇿
        - Denmark 🇩🇰
        - Estonia 🇪🇪
        - Finland 🇫🇮
        - France 🇫🇷
        - Germany 🇩🇪
        - Greece 🇬🇷
        - Hungary 🇭🇺
        - Iceland 🇮🇸
        - India 🇮🇳
        - Indonesia 🇮🇩
        - Ireland 🇮🇪
        - Israel 🇮🇱
        - Italy 🇮🇹
        - Japan 🇯🇵
        - Latvia 🇱🇻
        - Lithuania 🇱🇹
        - Luxembourg 🇱🇺
        - Malaysia 🇲🇾
        - Mexico 🇲🇽
        - Netherlands 🇳🇱
        - New Zealand 🇳🇿
        - Norway 🇳🇴
        - Poland 🇵🇱
        - Portugal 🇵🇹
        - Romania 🇷🇴
        - Russia 🇷🇺
        - Singapore 🇸🇬
        - Slovakia 🇸🇰
        - Slovenia 🇸🇮
        - South Africa 🇿🇦
        - South Korea 🇰🇷
        - Spain 🇪🇸
        - Sweden 🇸🇪
        - Switzerland 🇨🇭
        - Taiwan 🇹🇼
        - Thailand 🇹🇭
        - Turkey 🇹🇷
        - Ukraine 🇺🇦
        - United Kingdom 🇬🇧
        - United States 🇺🇸
        - Vietnam 🇻🇳
    validations:
      required: true
      
  - type: textarea
    id: screenshot_instructions
    attributes:
      label: Screenshot
      description: |
        Take a screenshot of your website:
        - Resolution: 1440 × 900 pixels
        - Format: PNG or JPG
        - Full page screenshot (not just a part)
        
        After creating the issue, simply drag and drop your screenshot here.
        
        💡 Tip: You can use tools like [Cleanshot](https://cleanshot.com) or your browser's built-in screenshot tool (cmd/ctrl + shift + 4 on macOS).
      placeholder: "Drag and drop your screenshot here after creating the issue."
    validations:
      required: true 